export const USER_ALREADY_SIGN_IN = 'User already sign in';
export const USER_ALREADY_LOGOUT = 'User logout';
export const SET_ALL_PRODUCTS = 'Set all products';
export const GET_INFO_ABOUT_PRODUCT = 'Get info about product';
export const ADD_SUBCATEGORIES = 'Add subcategories';
export const SET_USER_INFO = 'Set user info';
export const ADD_PRODUCT_TO_BASKET = 'Add product to basket';
export const SET_LANGUAGE_ENGLISH = 'Set language english';
export const SET_LANGUAGE_UKRAINE = 'Set language ukraine';
